<a href="https://colab.research.google.com/github/Rupeshh03/Machine-Learning-Project/blob/main/Iris_Flower_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset("iris")

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
df.isnull().sum().sum()

0

In [7]:
df.isnull()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [8]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
df1=df[df['species']!='setosa']

In [10]:
df1

sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[100 rows x 5 columns]

In [11]:
df1['species']=df1['species'].map({'versicolor':0, 'virginica':1})

<ipython-input-11-2e4c006cbd5a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['species']=df1['species'].map({'versicolor':0, 'virginica':1})


In [12]:
df1

sepal_length  sepal_width  petal_length  petal_width  species
50            7.0          3.2           4.7          1.4        0
51            6.4          3.2           4.5          1.5        0
52            6.9          3.1           4.9          1.5        0
53            5.5          2.3           4.0          1.3        0
54            6.5          2.8           4.6          1.5        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

[100 rows x 5 columns]

In [13]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [14]:
y=df1["species"]

In [15]:
X=df1.loc[:,df1.columns!="species"]

In [16]:
y.shape

(100,)

In [17]:
X.shape

(100, 4)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [19]:
X_train

sepal_length  sepal_width  petal_length  petal_width
61            5.9          3.0           4.2          1.5
97            6.2          2.9           4.3          1.3
135           7.7          3.0           6.1          2.3
78            6.0          2.9           4.5          1.5
143           6.8          3.2           5.9          2.3
..            ...          ...           ...          ...
110           6.5          3.2           5.1          2.0
121           5.6          2.8           4.9          2.0
64            5.6          2.9           3.6          1.3
142           5.8          2.7           5.1          1.9
101           5.8          2.7           5.1          1.9

[70 rows x 4 columns]

In [20]:
y_train

61     0
97     0
135    1
78     0
143    1
      ..
110    1
121    1
64     0
142    1
101    1
Name: species, Length: 70, dtype: int64

logistic regression

In [21]:
log_model=LogisticRegression()

In [22]:
log_model.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred=log_model.predict(X_test)

In [24]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1])

In [25]:
acc_log=round(accuracy_score(y_pred,y_test)*100,2)

In [26]:
print("Accuracy of Logistic Regression",acc_log)

Accuracy of Logistic Regression 93.33


##K Nearest Neighbor (KNN)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn_model=KNeighborsClassifier()

In [29]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [30]:
y_pred=knn_model.predict(X_test)

In [31]:
y_pred

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1])

In [32]:
acc_knn=round(accuracy_score(y_test,y_pred)*100,2)
print("Accuracy of K nearest Neighbors:", acc_knn)

Accuracy of K nearest Neighbors: 83.33


##Support Vector Machine ##

In [33]:
from sklearn import svm

In [34]:
svm_model=svm.SVC()

In [35]:
svm_model.fit(X_train,y_train)

SVC()

In [36]:
y_pred=svm_model.predict(X_test)

In [37]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1])

In [38]:
acc_svc=round(accuracy_score(y_test,y_pred)*100,2)
print('Accuracy of support vector classifier:',acc_svc)

Accuracy of support vector classifier: 90.0


###Decision Tree###

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dtree_model=DecisionTreeClassifier()

In [41]:
dtree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [42]:
y_pred=dtree_model.predict(X_test)

In [43]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [44]:
acc_dtree=round(accuracy_score(y_test,y_pred)*100,2)
print('Accuracy of Decison Tree Classifier:', acc_dtree)

Accuracy of Decison Tree Classifier: 76.67


###Random Forest

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rfc_model=RandomForestClassifier()


In [47]:
rfc_model.fit(X_train,y_train)

RandomForestClassifier()

In [48]:
y_pred=rfc_model.predict(X_test)

In [49]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1])

In [50]:
acc_rfc=round(accuracy_score(y_test,y_pred)*100,2)
print('Accuracy of Random forest Classifier:', acc_rfc)

Accuracy of Random forest Classifier: 83.33


###Model Selection

In [51]:
models=pd.DataFrame({
    'model':['Logistic Regression','Support vector Machine','K Nearest Neighbor','Decision Tree classifier','Random forest Classifier'],'score':[acc_log, acc_svc, acc_knn, acc_dtree, acc_rfc]
})

In [52]:
models.sort_values(by='score',ascending=False)

model  score
0       Logistic Regression  93.33
1    Support vector Machine  90.00
2        K Nearest Neighbor  83.33
4  Random forest Classifier  83.33
3  Decision Tree classifier  76.67